### ISSUE TITLE
No known class method for selector 

### ISSUE THREAD

**Issue by vzfintechgit** [adobe/flutter_griffon#4]
Hello, I'm working on a Flutter application to use Griffon on iOS, after add the dependency in pubspec.yaml and perform pub get the Podfile, I got `ACPGriffon` linked to my Xcode project.

flutter_griffon: ^1.0.0-beta.3

However, trying to compile got me several issues on `FlutterGriffonPlugin.m` class referring to a method selector that does not exist.

![Screen Shot 2020-09-24 at 4 55 08 PM](https://user-images.githubusercontent.com/68557405/94204367-bd1ba600-fe86-11ea-9e8f-c51e6275e960.png)

![Screen Shot 2020-09-24 at 4 55 58 PM](https://user-images.githubusercontent.com/68557405/94204422-d6bced80-fe86-11ea-8df3-2b2c3be0cfd9.png)

This is the Podfile.lock I got after ran pod install.

[Podfile_lock.txt](https://github.com/adobe/flutter_griffon/files/5279437/Podfile_lock.txt)

I noticed `ACPGriffon` interface only expose those methods.

+ (bool) registerExtension;

/**
 * @brief Provides the current version of Griffon SDK.
 *
 * @return a string representing the version of Griffon SDK
*/
+ (nonnull NSString*) extensionVersion;

/**
 * @brief Starts a Project Griffon session.
 *
 * Calling this method when a session has already been started will result in a no-op.
 * It will attempt to initiate a new Project Griffon session if no session is active.
 *
 * @param url a valid Project Griffon URL to start a session
 */
+ (void) startSession: (NSURL* _Nonnull) url;

It seems the plugging installed by flutter were expecting those methods on  `ACPGriffon`.

I'm no sure if I'm making the configuration in the correct way, installing the ACPGriffon using pod has not raised this error, it only appear when I tried to use it from flutter through `  flutter_griffon: ^1.0.0-beta.3` dependency.

**Comment by PravinPK** [comment]
Hi @vzfintechgit , 
The flutter_griffon package has been deprecated https://pub.dev/packages/flutter_griffon
We have rebranded to Flutter Assurance: https://pub.dev/packages/flutter_assurance

And the latest release to Assurance has been made supporting Flutter 2 and null safety. Feel free to reopen if you are still facing issues with the latest package.

Thanks,
Pravin Prakash Kumar
