### ISSUE TITLE
Error running on Android

### ISSUE THREAD

**Issue by mposada** [adobe/flutter_griffon#5]
`
Running Gradle task 'assembleDevDebug'...
/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_griffon-1.0.0-beta.3/android/src/main/java/com/adobe/marketing/mobile/flutter/FlutterGriffonDataBridge.java:18: error: cannot find symbol
    static Griffon.UILogColorVisibility getVisibilityFromInt(String visibility) {
                  ^
  symbol:   class UILogColorVisibility
  location: class Griffon
/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_griffon-1.0.0-beta.3/android/src/main/java/com/adobe/marketing/mobile/flutter/FlutterGriffonPlugin.java:17: error: GriffonEvent is not public in com.adobe.marketing.mobile; cannot be accessed from outside package
import com.adobe.marketing.mobile.GriffonEvent;
                                 ^
/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_griffon-1.0.0-beta.3/android/src/main/java/com/adobe/marketing/mobile/flutter/FlutterGriffonDataBridge.java:20: error: cannot find symbol
            case "ACPGRIFFON_UI_LOG_COLOR_LOW": return Griffon.UILogColorVisibility.LOW;
                                                              ^
  symbol:   variable UILogColorVisibility
  location: class Griffon
/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_griffon-1.0.0-beta.3/android/src/main/java/com/adobe/marketing/mobile/flutter/FlutterGriffonDataBridge.java:21: error: cannot find symbol
            case "ACPGRIFFON_UI_LOG_COLOR_NORMAL": return Griffon.UILogColorVisibility.NORMAL;
                                                                 ^
  symbol:   variable UILogColorVisibility
  location: class Griffon
/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_griffon-1.0.0-beta.3/android/src/main/java/com/adobe/marketing/mobile/flutter/FlutterGriffonDataBridge.java:22: error: cannot find symbol
            case "ACPGRIFFON_UI_LOG_COLOR_HIGH": return Griffon.UILogColorVisibility.HIGH;
                                                               ^
  symbol:   variable UILogColorVisibility
  location: class Griffon
/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_griffon-1.0.0-beta.3/android/src/main/java/com/adobe/marketing/mobile/flutter/FlutterGriffonDataBridge.java:23: error: cannot find symbol
            case "ACPGRIFFON_UI_LOG_COLOR_CRITICAL": return Griffon.UILogColorVisibility.CRITICAL;
                                                                   ^
  symbol:   variable UILogColorVisibility
  location: class Griffon
/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_griffon-1.0.0-beta.3/android/src/main/java/com/adobe/marketing/mobile/flutter/FlutterGriffonPlugin.java:52: error: cannot find symbol
      Griffon.endSession();
             ^
  symbol:   method endSession()
  location: class Griffon
/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_griffon-1.0.0-beta.3/android/src/main/java/com/adobe/marketing/mobile/flutter/FlutterGriffonPlugin.java:58: error: cannot find symbol
      Griffon.attemptReconnect();
             ^
  symbol:   method attemptReconnect()
  location: class Griffon
/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_griffon-1.0.0-beta.3/android/src/main/java/com/adobe/marketing/mobile/flutter/FlutterGriffonPlugin.java:76: error: cannot find symbol
        GriffonEvent event = new GriffonEvent(vendor, type, payload);
        ^
  symbol:   class GriffonEvent
  location: class FlutterGriffonPlugin
/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_griffon-1.0.0-beta.3/android/src/main/java/com/adobe/marketing/mobile/flutter/FlutterGriffonPlugin.java:76: error: cannot find symbol
        GriffonEvent event = new GriffonEvent(vendor, type, payload);
                                 ^
  symbol:   class GriffonEvent
  location: class FlutterGriffonPlugin
/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_griffon-1.0.0-beta.3/android/src/main/java/com/adobe/marketing/mobile/flutter/FlutterGriffonPlugin.java:92: error: cannot find symbol
    Griffon.UILogColorVisibility visibility = FlutterGriffonDataBridge.getVisibilityFromInt(visibilityInInt);
           ^
  symbol:   class UILogColorVisibility
  location: class Griffon
11 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_griffon:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Exception: Gradle task assembleDevDebug failed with exit code 1
`

**Comment by PravinPK** [comment]
Hi @mposada, 
The flutter_griffon package has been deprecated https://pub.dev/packages/flutter_griffon
We have rebranded to Flutter Assurance: https://pub.dev/packages/flutter_assurance

And the latest release to Assurance has been made supporting Flutter 2 and null safety. Feel free to reopen if you are still facing issues with the latest package.

Thanks,
Pravin Prakash Kumar
